function [fXdeconvoluted, xx, Q] = decon_err_sym(W, xx)

    if ~exist('xx','var')
        xx = linspace(min(W), max(W), 100);
    end

    % Deconvolve to pmf --------------------------------------------------------
    m = 20;
    n_tp_iter = 5;
    n_var_iter = 2;
    [Q, tt, normhatphiW] = decon_err_sym_pmf(W, ...
                                             m, ...
                                             n_tp_iter, ...
                                             n_var_iter);

    % Convert pmf to pdf -------------------------------------------------------    
    fXdeconvoluted = decon_err_sym_pmf2pdf(xx, ...
                                           tt, ...
                                           Q.Support, ...
                                           Q.ProbWeights, ...
                                           W, ...
                                           normhatphiW);
end